### ISSUE TITLE
Question: Will do you add subfolder support?

### ISSUE THREAD

**Issue by novafacile** [Neoflow/Filery#10]
Hi,

Filery is a really great plugin for TinyMCE! Thanks a lot for that!  :thumbsup:

Do you plan to add subfolder support (add subfolder or browse into a subfolder)? This would help to manage the files and would made the great plugin absolute perfect.  :wink:

**Comment by rjgamer** [comment]
I am glad to hear that you like my work :) And I knew it already, that if Filery will be liked by the users, the question of subfolder support will pop up.

I'm planning to implement the support in coming next minor release (1.3). But please dont ask for any date :)

**Comment by rjgamer** [comment]
Please follow now the #11 or [projectboard ](https://github.com/Neoflow/Filery/projects/4) to get the latest updates (e.g. code commits or feature complete state).
