### ISSUE TITLE
1.3 release

### ISSUE THREAD

**Issue by Fzoltan87** [Neoflow/Filery#13]
Hay,

When is the release of version 1.3 expected?
Do you already have any information about it?

Thanks

**Comment by rjgamer** [comment]
Low motivation here ;-) Give me please a few reasons to motivate me... For what do you need Filery?

**Comment by Fzoltan87** [comment]
The previously mentioned folder management (creation, modification and deletion - possibly renaming a folder) would be interesting.

**Comment by rjgamer** [comment]
For market purpose: Would you spend a few cents to get this feature?

Example: 5$ per domain or 99$ per company/person as one time fee

**Comment by Fzoltan87** [comment]
Have you paid for this application? Or paid for this supplement?

**Comment by rjgamer** [comment]
I'm the developer of Filery and currently not motivated to add a folder support. I only want to know if you would spend a few bucks to motivate me for getting your folder support faster.

**Comment by rjgamer** [comment]
Dont forget: I am doing this in my free time and not professional.
