### ISSUE TITLE
401 Unauthorized response

### ISSUE THREAD

**Issue by netsenior** [Neoflow/Filery#14]
Hi there, 
its probably a dump thing... but I´m getting a 401 Unauthorized response from plugins/filery/api/index.php ... I see the Token at the console and I´m confused about "authenticated users". Is it related to the tinymce api key?!

thanks!!!

**Comment by rjgamer** [comment]
Sorry mate. I cannot help you without more details like screenshots and log entries.

Please provide more information.

**Comment by netsenior** [comment]
hey Jonathan, 

its TinyMCE 4.8.5 and attached there is a screenshot. 

Let me know if need more details and thanks for the help!

PS: the TinyMCE's api key is not the same as the X-Filery-Token in the screenshot.

![Untitled-1](https://user-images.githubusercontent.com/5733923/64020379-d4fbeb80-cb07-11e9-852a-aef3b77f4d85.jpg)

**Comment by rjgamer** [comment]
No code no help. And actually issues are for error reports and not for support requests.

**Comment by rjgamer** [comment]
Please read again the installation capter 2 and recheck your API and Filery configuration: https://github.com/Neoflow/Filery/blob/master/README.md#2-plugin-api

**Comment by rjgamer** [comment]
The source of your 401 error can be found here:
https://github.com/Neoflow/Filery/blob/master/api/classes/Filery/AbstractAPI.php#L90

Did you start a session with session_start()? Because the API is verifying the token based on the secret key in $_SESSION.

**Comment by netsenior** [comment]
I´ve commented the session_start() because the CI framework have started it already...
attached is this portion of the code.
![Untitled-1](https://user-images.githubusercontent.com/5733923/64024517-f4e3dd00-cb10-11e9-95f7-3164110d8193.jpg)

**Comment by rjgamer** [comment]
Ok. CI is handling your session and not PHP. Per default the API is creating a new PHP-based session and is not using your CI session.

You have to customize the Token class and get the session data from CI (line 28 - 39) in here: https://github.com/Neoflow/Filery/blob/master/api/classes/Filery/Token.php#L28

Some day I will refactored the API to support this mismatch with third party created sessions. But for now you have to customize the Token class by yourself. Sorry.

**Comment by rjgamer** [comment]
Its done when its done: https://github.com/Neoflow/Filery/issues/15
