### ISSUE TITLE
File manager window is cropped on my smartphone

### ISSUE THREAD

**Issue by twister65** [Neoflow/Filery#9]
When I click the File Manager button on the demo site, I see the dialog box partially and can not close it.
This window is not responsive.

**Comment by rjgamer** [comment]
Thanks for your feedback!

Filery is using the UI of TinyMCE for the dialog. Unfortunately, the dialogs are not responsive, so the dialog of Filery cannot be responsive too. But I'm planning a mobile-friendly version, when the mobile UI of TinyMCE is open for public use and well documented (but currently not).

**Comment by rjgamer** [comment]
Hi again. TinyMCE 5 incoming, which is responsive: https://www.tiny.cloud/developer-preview/

Get ready for a Filery release for TinyMCE 5 with responsiveness. But I will wait for the development until TinyMCE 5 as finale version is released.
